[versions]
assertj = "3.27.6"
gradleOci-junitJupiter = "0.8.0"
hivemq-extensionSdk = "4.29.0"
hivemq-mqttClient = "1.3.12"
jackson = "2.20.1"
jackson-asl = "1.9.13"
jetbrains-annotations = "26.0.2-1"
junit-jupiter = "5.10.0"
logback = "1.5.24"
mockito = "5.21.0"
protobuf = "3.25.8"
tahu = "1.0.14"
testcontainers = "2.0.3"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
gradleOci-junitJupiter = { module = "io.github.sgtsilvio:gradle-oci-junit-jupiter", version.ref = "gradleOci-junitJupiter" }
hivemq-mqttClient = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemq-mqttClient" }
jackson = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-mapper-asl = { module = "org.codehaus.jackson:jackson-mapper-asl", version.ref = "jackson-asl" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
protobuf = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
tahu = { module = "org.eclipse.tahu:tahu-core", version.ref = "tahu" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-hivemq = { module = "org.testcontainers:testcontainers-hivemq", version.ref = "testcontainers" }
testcontainers-junitJupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }

[plugins]
checksum = { id = "org.gradle.crypto.checksum", version = "1.4.0" }
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
hivemq-extension = { id = "com.hivemq.extension", version = "4.0.0" }
license = { id = "com.github.hierynomus.license", version = "0.16.1" }
oci = { id = "io.github.sgtsilvio.gradle.oci", version = "0.24.0" }
release = { id = "net.researchgate.release", version = "3.1.0" }
